import 'dart:ui';

const Color GREEN_BUTTON_COLOR = Color(0xFF00C89B);
const Color RED_BUTTON_COLOR = Color(0xFFFF605C);
const Color BOTTOM_APP_BAR_BACKGROUND_COLOR = Color(0xFFF4ECFF);
const Color FEED_BACKGROUND_COLOR = Color(0XFF292C6D);
